spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meeting_ha_ja?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: tjddnr12
  thymeleaf:
    cache: false

  # spring data jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

# swagger setting
springdoc:
  packages-to-scan: com.example.controller
  default-consumes-media-type: application/json; charset=UTF-8
  default-produces-media-type: application/json; charset=UTF-8

# AWS S3
cloud:
  aws:
    s3:
      bucket: asd
      stack.auto: false
      region.static: us-east-1
      credentials:
        accessKey: AKIAQQTPC6YH6JVNTDID
        secretKey: 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