# AWS S3
cloud:
  aws:
    s3:
      bucket: asd
      stack.auto: false
      region.static: us-east-1
      credentials:
        accessKey: "accessKey"
        secretKey: "secretKey"

# JWT
jwt:
  token:
    secret: "secretKey"